[package]
name = "world-editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nexus-assets.workspace   = true
nexus-core.workspace     = true
nexus-platform.workspace = true
nexus-render.workspace   = true
nexus-sim.workspace      = true
nexus-script.workspace   = true
nexus-render-wgpu        = { workspace = true, features = ["ui"] }

egui.workspace       = true
egui-winit.workspace = true
png.workspace        = true
serde.workspace      = true
ron.workspace        = true

[lints]
workspace = true
